name: Deploy to Railway

on:
  push:
    paths:
      - prisma/migrations/**
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    container: ghcr.io/railwayapp/cli:latest
    env:
      SVC_ID: 4720fcd0-a596-4355-a74c-789dbf32aeff
      RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
      - name: Install dependencies
        run: pnpm install
      - name: Apply all pending migrations to the database
        run: pnpm exec prisma migrate deploy
      - run: railway up --service=${{ env.SVC_ID }}
